# source: https://github.com/ThewApp/speedlify-actions-vercel/blob/main/.github/workflows/deploy-vercel.yml
# sequential workflow reference: https://stevenmortimer.com/running-github-actions-sequentially/

name: Deploy to Vercel

# on:
#   push:
#   workflow_dispatch:
#   schedule:
    - cron: "0 */6 * * *"

on:
  repository_dispatch:
    types: [trigger-deploy-speedlify-vercel]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results
        uses: actions/checkout@v2
        with:
          ref: refs/heads/results
          path: results
      - name: Checkout speedlify
        uses: actions/checkout@v2
        with:
          path: default
      - name: Copy existing results
        run: cp -r results/. default/_data
      - run: |
          mkdir .vercel
          echo $VERCEL_PROJECT > .vercel/project.json
          npx vercel --prod --token $VERCEL_TOKEN
        working-directory: default
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}
