# .github/workflows/main.yml

name: Trigger Netlify Build daily on Weekday
on:
  schedule:
    # Every 20 minutes
    - cron: '0 22 * * MON-FRI'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5fa6e0b6f8b3ba6eb4702b36